"""initial schema

Revision ID: 800a36764d25
Revises: 
Create Date: 2026-05-12 04:39:53.757957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800a36764d25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Reconciliation migration — makes the schema match the ORM models.
    Uses IF EXISTS throughout since the DO DB was created from schema.sql
    directly and may have different constraint/index names.
    """
    conn = op.get_bind()

    # Drop indexes if they exist
    for idx in [
        'idx_matchups_round', 'idx_matchups_session',
        'idx_pokemon_evolution_stage', 'idx_pokemon_generation',
        'idx_pokemon_legendary', 'idx_pokemon_mythical',
        'idx_pokemon_types_type', 'idx_session_pokemon_session',
    ]:
        conn.execute(sa.text(f'DROP INDEX IF EXISTS {idx}'))

    # Drop old unique constraint on rounds if it exists
    conn.execute(sa.text('''
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'rounds_session_id_round_number_key'
            ) THEN
                ALTER TABLE rounds
                DROP CONSTRAINT rounds_session_id_round_number_key;
            END IF;
        END $$
    '''))

    # Create the correctly named unique constraint if it doesn't exist
    conn.execute(sa.text('''
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_rounds_session_round'
            ) THEN
                ALTER TABLE rounds
                ADD CONSTRAINT uq_rounds_session_round
                UNIQUE (session_id, round_number);
            END IF;
        END $$
    '''))

    # Update enum columns — alter only if they're still varchar
    conn.execute(sa.text('''
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'session_pokemon'
                AND column_name = 'status'
                AND data_type = 'character varying'
            ) THEN
                ALTER TABLE session_pokemon
                ALTER COLUMN status TYPE varchar(20);
            END IF;
        END $$
    '''))

    conn.execute(sa.text('''
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'sessions'
                AND column_name = 'status'
                AND data_type = 'character varying'
            ) THEN
                ALTER TABLE sessions
                ALTER COLUMN status TYPE varchar(20);
            END IF;
        END $$
    '''))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.Enum('active', 'completed', 'abandoned', name='session_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('idx_session_pokemon_session'), 'session_pokemon', ['session_id', 'status'], unique=False)
    op.alter_column('session_pokemon', 'status',
               existing_type=sa.Enum('active', 'eliminated', 'winner', name='pokemon_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('uq_rounds_session_round', 'rounds', type_='unique')
    op.create_unique_constraint(op.f('rounds_session_id_round_number_key'), 'rounds', ['session_id', 'round_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pokemon_types_type'), 'pokemon_types', ['type'], unique=False)
    op.alter_column('pokemon_types', 'type',
               existing_type=sa.Enum('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum', native_enum=False),
               type_=postgresql.ENUM('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum'),
               existing_nullable=False)
    op.create_index(op.f('idx_pokemon_mythical'), 'pokemon', ['is_mythical'], unique=False)
    op.create_index(op.f('idx_pokemon_legendary'), 'pokemon', ['is_legendary'], unique=False)
    op.create_index(op.f('idx_pokemon_generation'), 'pokemon', ['generation'], unique=False)
    op.create_index(op.f('idx_pokemon_evolution_stage'), 'pokemon', ['evolution_stage'], unique=False)
    op.create_index(op.f('idx_matchups_session'), 'matchups', ['session_id'], unique=False)
    op.create_index(op.f('idx_matchups_round'), 'matchups', ['round_id'], unique=False)
    # ### end Alembic commands ###
