"""initial schema

Revision ID: 800a36764d25
Revises: 
Create Date: 2026-05-12 04:39:53.757957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800a36764d25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_matchups_round'), table_name='matchups')
    op.drop_index(op.f('idx_matchups_session'), table_name='matchups')
    op.drop_index(op.f('idx_pokemon_evolution_stage'), table_name='pokemon')
    op.drop_index(op.f('idx_pokemon_generation'), table_name='pokemon')
    op.drop_index(op.f('idx_pokemon_legendary'), table_name='pokemon')
    op.drop_index(op.f('idx_pokemon_mythical'), table_name='pokemon')
    op.alter_column('pokemon_types', 'type',
               existing_type=postgresql.ENUM('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum'),
               type_=sa.Enum('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('idx_pokemon_types_type'), table_name='pokemon_types')
    op.drop_constraint(op.f('rounds_session_id_round_number_key'), 'rounds', type_='unique')
    op.create_unique_constraint('uq_rounds_session_round', 'rounds', ['session_id', 'round_number'])
    op.alter_column('session_pokemon', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'eliminated', 'winner', name='pokemon_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_session_pokemon_session'), table_name='session_pokemon')
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'completed', 'abandoned', name='session_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.Enum('active', 'completed', 'abandoned', name='session_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('idx_session_pokemon_session'), 'session_pokemon', ['session_id', 'status'], unique=False)
    op.alter_column('session_pokemon', 'status',
               existing_type=sa.Enum('active', 'eliminated', 'winner', name='pokemon_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('uq_rounds_session_round', 'rounds', type_='unique')
    op.create_unique_constraint(op.f('rounds_session_id_round_number_key'), 'rounds', ['session_id', 'round_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pokemon_types_type'), 'pokemon_types', ['type'], unique=False)
    op.alter_column('pokemon_types', 'type',
               existing_type=sa.Enum('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum', native_enum=False),
               type_=postgresql.ENUM('normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting', 'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy', name='pokemon_type_enum'),
               existing_nullable=False)
    op.create_index(op.f('idx_pokemon_mythical'), 'pokemon', ['is_mythical'], unique=False)
    op.create_index(op.f('idx_pokemon_legendary'), 'pokemon', ['is_legendary'], unique=False)
    op.create_index(op.f('idx_pokemon_generation'), 'pokemon', ['generation'], unique=False)
    op.create_index(op.f('idx_pokemon_evolution_stage'), 'pokemon', ['evolution_stage'], unique=False)
    op.create_index(op.f('idx_matchups_session'), 'matchups', ['session_id'], unique=False)
    op.create_index(op.f('idx_matchups_round'), 'matchups', ['round_id'], unique=False)
    # ### end Alembic commands ###
